{
  "formatVersion": "1.1",
  "component": {
    "group": "com.michaelgrundvig.frc",
    "module": "spotter-client",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.michaelgrundvig.frc",
          "module": "spotter-api",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotter-client-0.3.0.jar",
          "url": "spotter-client-0.3.0.jar",
          "size": 40148,
          "sha512": "de8b1fb436fef9b9903dd694cfec0ec7609a1e96d5c7cf01d13256842902c086f796bd9c919b796a0537383908d4c6f4d19db54e86e33f1034dab1c92421a008",
          "sha256": "04b92dce98f1f62d0b52f19d3193b50e95ee7751ec512620a5df48831ea3c243",
          "sha1": "a5cce35f427d6b79acf62619a871ce5f879f5bda",
          "md5": "89fd55337bd35b54ec952954b20fe98d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.michaelgrundvig.frc",
          "module": "spotter-api",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotter-client-0.3.0.jar",
          "url": "spotter-client-0.3.0.jar",
          "size": 40148,
          "sha512": "de8b1fb436fef9b9903dd694cfec0ec7609a1e96d5c7cf01d13256842902c086f796bd9c919b796a0537383908d4c6f4d19db54e86e33f1034dab1c92421a008",
          "sha256": "04b92dce98f1f62d0b52f19d3193b50e95ee7751ec512620a5df48831ea3c243",
          "sha1": "a5cce35f427d6b79acf62619a871ce5f879f5bda",
          "md5": "89fd55337bd35b54ec952954b20fe98d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotter-client-0.3.0-sources.jar",
          "url": "spotter-client-0.3.0-sources.jar",
          "size": 16838,
          "sha512": "77b5e82d12fc6ce5cc72bb97baf0c96de8ae6f6d073a3bfe24e4362e4ab9360a9616a04aa4387da274f64911e10ee00b37c710c95345652081092cc40731e5b1",
          "sha256": "c65011951716e4e16ac7208d7d8dd96a2c01277330d8f07a78a1ae3433c11d10",
          "sha1": "03a7acb31911275c125ecc3ef4dbc3ea5c7a6a80",
          "md5": "06b705e1c0eba87abb03a03d759d60a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotter-client-0.3.0-javadoc.jar",
          "url": "spotter-client-0.3.0-javadoc.jar",
          "size": 4255111,
          "sha512": "21e927df2759e39ea73037f0c3d3df73cda0f38cc7018e50f6a916344f8948e9bcf0b2b6f4e71bde688fda87618b64a529057225bda6cc31176c7b88e361c4d7",
          "sha256": "609217e3ae5426b09854557feaa2b5ca2244e137015a76f554c988a4d9b17bbd",
          "sha1": "1e9fa0b809eea6382ae37f9bee2dbd9e31d63e22",
          "md5": "e98b9f9670ed20d9646048c4513b1fc2"
        }
      ]
    }
  ]
}
