-- Rows as PhotonVision writes them (SqlConfigProvider.saveGlobal and saveCameras): each column one
-- line of JSON, members in each class's field order, and the legacy camera columns written as
-- "null" and "[]". The values are an example of a configured coprocessor, written from the
-- classes' fields (CameraConfiguration, PVCameraInfo, QuirkyCamera, CVPipelineSettings,
-- CameraCalibrationCoefficients, NetworkConfig, HardwareConfig, HardwareSettings), not copied from
-- a real board.
INSERT INTO global (filename, contents) VALUES ('hardwareSettings', '{"ledBrightnessPercentage":100}');
INSERT INTO global (filename, contents) VALUES ('networkConfig', '{"ntServerAddress":"1234","connectionType":"DHCP","staticIp":"","hostname":"vision-front","runNTServer":false,"shouldManage":false,"shouldPublishProto":false,"networkManagerIface":"","setStaticCommand":"","setDHCPcommand":""}');
INSERT INTO global (filename, contents) VALUES ('hardwareConfig', '{"deviceName":"","ledPins":[],"ledsCanDim":false,"ledBrightnessRange":[0,100],"ledPWMFrequency":0,"getGPIOCommand":"","setGPIOCommand":"","setPWMCommand":"","setPWMFrequencyCommand":"","releaseGPIOCommand":"","restartHardwareCommand":"","vendorFOV":-1.0}');
INSERT INTO global (filename, contents) VALUES ('neuralNetworkProperties', '{"models":[]}');
INSERT INTO global (filename, contents) VALUES ('fieldLayout', '{"name":"2026-rebuilt-welded","tags":[{"ID":1,"pose":{"translation":{"x":11.8779,"y":7.4247,"z":0.889},"rotation":{"quaternion":{"W":6.123233995736766E-17,"X":0.0,"Y":0.0,"Z":1.0}}}}],"field":{"length":16.541,"width":8.069}}');
INSERT INTO cameras (unique_name, config_json, drivermode_json, pipeline_jsons, otherpaths_json) VALUES (
 '3e5a7c41-9d2b-4f60-8a1e-5b7c9d0e2f13',
 '{"uniqueName":"3e5a7c41-9d2b-4f60-8a1e-5b7c9d0e2f13","matchedCameraInfo":{"type":"PVUsbCameraInfo","dev":0,"path":"/dev/video0","name":"Arducam OV9281 USB Camera","otherPaths":["/dev/v4l/by-path/platform-xhci-hcd.0.auto-usb-0:1:1.0-video-index0","/dev/v4l/by-id/usb-Arducam_Technology_Co.__Ltd._Arducam_OV9281_USB_Camera_UC762-video-index0"],"vendorId":3141,"productId":25446},"nickname":"front-left","deactivated":false,"cameraQuirks":{"baseName":"OV9281","usbVid":3141,"usbPid":25446,"displayName":"Arducam OV9281","quirks":{"ArduOV9281Controls":true,"Gain":true,"AwbRedBlueGain":false}},"FOV":70.0,"calibrations":[{"resolution":{"width":1280.0,"height":800.0},"cameraIntrinsics":{"rows":3,"cols":3,"type":6,"data":[905.4,0.0,641.2,0.0,905.1,398.7,0.0,0.0,1.0]},"distCoeffs":{"rows":1,"cols":8,"type":6,"data":[0.051,-0.083,1.2E-4,-3.0E-4,0.021,0.0,0.0,0.0]},"observations":[{"locationInObjectSpace":[{"x":0.0,"y":0.0,"z":0.0},{"x":0.0254,"y":0.0,"z":0.0}],"locationInImageSpace":[{"x":312.5,"y":207.25},{"x":341.0,"y":207.5}],"reprojectionErrors":[{"x":0.12,"y":-0.08},{"x":-0.05,"y":0.11}],"optimisedCameraPose":{"translation":{"x":0.1,"y":-0.05,"z":0.6},"rotation":{"quaternion":{"W":0.99,"X":0.01,"Y":0.1,"Z":0.0}}},"includeObservationInCalibration":true,"snapshotName":"img0.png"}],"calobjectWarp":[1.0E-5,-2.0E-5],"calobjectSize":{"width":8.0,"height":8.0},"calobjectSpacing":0.0254,"lensmodel":"LENSMODEL_OPENCV"}],"currentPipelineIndex":0,"streamIndex":0,"pipelineSettings":[{"type":"AprilTagPipelineSettings","pipelineIndex":0,"inputImageRotationMode":"DEG_0","pipelineNickname":"tags","cameraAutoExposure":false,"cameraExposureRaw":12.0,"cameraMinExposureRaw":1.0,"cameraMaxExposureRaw":100.0,"cameraBrightness":50,"cameraGain":75,"cameraRedGain":11,"cameraBlueGain":20,"cameraVideoModeIndex":3,"streamingFrameDivisor":"NONE","ledMode":false,"inputShouldShow":false,"outputShouldShow":true,"cameraAutoWhiteBalance":false,"cameraWhiteBalanceTemp":4000.0,"blockForFrames":true,"tagFamily":"kTag36h11","decimate":2,"blur":0.0,"threads":4,"debug":false,"refineEdges":true,"numIterations":40,"decisionMargin":35,"hammingDist":0,"doMultiTarget":true,"doSingleTargetAlways":false}],"driveModeSettings":{"type":"DriverModePipelineSettings","pipelineIndex":-1,"pipelineNickname":"Driver Mode","cameraAutoExposure":true}}',
 'null',
 '[]',
 '[]');
INSERT INTO cameras (unique_name, config_json, drivermode_json, pipeline_jsons) VALUES (
 'front right',
 '{"uniqueName":"front right","matchedCameraInfo":{"type":"PVUsbCameraInfo","dev":2,"path":"/dev/video2","name":"Arducam OV9281 USB Camera","otherPaths":["/dev/v4l/by-path/platform-xhci-hcd.1.auto-usb-0:1:1.0-video-index0"],"vendorId":3141,"productId":25446},"nickname":"front-right","deactivated":false,"FOV":70.0,"calibrations":[],"currentPipelineIndex":1,"streamIndex":1,"pipelineSettings":[],"driveModeSettings":{"type":"DriverModePipelineSettings","pipelineIndex":-1}}',
 'null',
 '[]');
